### ISSUE TITLE
Marker on map.geo.admin.ch (CF) are not accessible

### ISSUE THREAD

**Issue by procrastinatio** [geoadmin/service-print#29] opened 2017-04-27 13:02 UTC
Behind AWS CF the print server fails to print the marker:
- mf-geoadmin3.int.bgdi.ch
- map.geo.admin.ch

Behing ELB, the markers are printed
- mf-geoadmin3.dev.bgdi.ch
- mf-geoadmin3.prod.bgdi.ch

Print server cannot access this:

```
 curl -o /dev/null -v  \ 
https://map.geo.admin.ch/master/688362f/1704261351/1704261351/img/marker.png

< HTTP/1.1 200 OK
< Content-Type: image/png
< Content-Length: 808
< Connection: keep-alive
< Date: Thu, 27 Apr 2017 12:57:10 GMT
< Last-Modified: Wed, 26 Apr 2017 14:30:31 GMT
< ETag: "4726d3d21bd8711c62b18164d48813eb"
< Cache-Control: max-age=31536000, public
< Accept-Ranges: bytes
< Server: AmazonS3
< X-Cache: Miss from cloudfront
< Via: 1.1 d06fda6fd534830cffddb026cd65d045.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: AZ7DJPYgxoCbEBdQdueO4IrI--81ucEzQ84NbAvYNWzrnc4UWvqhvA==

```

while the same via `S3`is OK:
```
 curl -o /dev/null -v  https://mf-geoadmin3.prod.bgdi.ch/master/688362f/1704261351/1704261351/img/marker.png

< HTTP/1.1 200 OK
< Accept-Ranges: bytes
< Access-Control-Allow-Origin: *
< Age: 823
< Cache-Control: max-age=31536000, public
< Content-Type: image/png
< Date: Thu, 27 Apr 2017 12:48:56 GMT
< ETag: "4726d3d21bd8711c62b18164d48813eb"
< Last-Modified: Wed, 26 Apr 2017 14:30:31 GMT
< Server: AmazonS3
< Via: 1.1 varnish-v4
< X-Cache: HIT
< X-Cache-Hits: 1
< X-Varnish: 32467448 39455291
< Content-Length: 808
< Connection: keep-alive

```
All files are accessed via curl without any issue from everywhere.

**Comment by procrastinatio** [comment] 2017-05-04 14:53
The print server is not able to get the marker, and gives up after a timeout of 60 seconds.

Running the code manually, we get a `Received fatal alert: handshake_failure` exception while trying to download the image:

```
$ java -Djava.awt.headless=true -cp build/libs/print-standalone-2.1-SNAPSHOT.jar  org.mapfish.print.ShellMapPrinter --config=$HOME/service-print/tomcat/config.yaml --spec=$HOME/print-examples/external-marker.json --output=$HOME/external-marker.pdf

2017-05-04 16:10:32,094 [tilesReader0] ERROR     org.mapfish.print.PDFUtils - Server returned an error for https://map.geo.admin.ch/master/688362f/1704261351/1704261351/img/marker.png: Received fatal alert: handshake_failure
2017-05-04 16:11:31,559 [ajp-bio-8009-exec-6] DEBUG h.print.servlet.BaseMapServlet - Using 'null' to encode Inputcontent.
2017-05-04 16:11:31,560 [ajp-bio-8009-exec-6] ERROR h.print.servlet.BaseMapServlet - Error while generating PDF
java.io.IOException: Socket read failed
    at org.apache.coyote.ajp.AjpProcessor.read(AjpProcessor.java:313)
    at org.apache.coyote.ajp.AjpProcessor.readMessage(AjpProcessor.java:364)
    at org.apache.coyote.ajp.AjpProcessor.receive(AjpProcessor.java:331)
    at org.apache.coyote.ajp.AbstractAjpProcessor$SocketInputBuffer.doRead(AbstractAjpProcessor.java:1073)
    at org.apache.coyote.Request.doRead(Request.java:422)
    at org.apache.catalina.connector.InputBuffer.realReadBytes(InputBuffer.java:290)
    at org.apache.tomcat.util.buf.ByteChunk.substract(ByteChunk.java:431)
    at org.apache.catalina.connector.InputBuffer.read(InputBuffer.java:315)
    at org.apache.catalina.connector.CoyoteInputStream.read(CoyoteInputStream.java:200)
    at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:283)
    at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:325)
    at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:177)
    at java.io.InputStreamReader.read(InputStreamReader.java:184)
    at java.io.BufferedReader.fill(BufferedReader.java:154)
    at java.io.BufferedReader.read1(BufferedReader.java:205)
    at java.io.BufferedReader.read(BufferedReader.java:279)
    at java.io.Reader.read(Reader.java:100)
    at com.google.common.io.CharStreams.copy(CharStreams.java:176)
    at com.google.common.io.CharStreams.toStringBuilder(CharStreams.java:220)
    at com.google.common.io.CharStreams.toString(CharStreams.java:194)
    at org.mapfish.print.servlet.MapPrinterServlet.getSpecFromPostBody(MapPrinterServlet.java:232)
    at org.mapfish.print.servlet.MapPrinterServlet.createPDF(MapPrinterServlet.java:180)
    at org.mapfish.print.servlet.MapPrinterServlet.doPost(MapPrinterServlet.java:109)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:641)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:225)


```

**Comment by procrastinatio** [comment] 2017-05-04 15:58
Some CF distribution are OK though:

This marker is OK:
https://dfa30utos8zzp.cloudfront.net/1455526563/img/marker.png

```
> GET /1455526563/img/marker.png HTTP/1.1
> Host: dfa30utos8zzp.cloudfront.net
> User-Agent: curl/7.38.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: image/png
< Content-Length: 808
< Connection: keep-alive
< Date: Thu, 04 May 2017 15:54:59 GMT
< Last-Modified: Mon, 15 Feb 2016 09:00:27 GMT
< ETag: "4726d3d21bd8711c62b18164d48813eb"
< Cache-Control: max-age=31536000, public
< Accept-Ranges: bytes
< Server: AmazonS3
< X-Cache: Miss from cloudfront
< Via: 1.1 b4b6d30e349cbed36f8141249dcef99f.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: ARrIfJ8NIOjAyBYijdYOnv90dFxcTPbNkYMTThk_SPYy4PQsutjqcw==
```

**Comment by procrastinatio** [comment] 2017-05-04 16:09
Hem...
- It is not the certificate, as all certificates are pretty the same, or maybe not (?)
- It is not AWS CF _per_se_, as some distro are OK
- It is not a network issue
- No referrer issue
- Not the code returning error, a simple example show it download the image without problem
- Probalby not tomcat, as running it standalone conistenlty fail

Compare, in particular the handhake simulation:
https://www.ssllabs.com/ssltest/analyze.html?d=map.geo.admin.ch&s=52.84.0.8&latest
with 
https://www.ssllabs.com/ssltest/analyze.html?d=mf-geoadmin3.prod.bgdi.ch&s=54.194.224.237&latest

**Comment by danduk82** [comment] 2017-05-05 08:28
I cannot reproduce; from my home it seems to work:

curl -o /dev/null -v https://map.geo.admin.ch/master/688362f/1704261351/1704261351/img/marker.png
* Hostname was NOT found in DNS cache
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 13.32.176.160...
* Connected to map.geo.admin.ch (13.32.176.160) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Server hello (2):
{ [data not shown]
* SSLv3, TLS handshake, CERT (11):
{ [data not shown]
* SSLv3, TLS handshake, Server key exchange (12):
{ [data not shown]
* SSLv3, TLS handshake, Server finished (14):
{ [data not shown]
* SSLv3, TLS handshake, Client key exchange (16):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
} [data not shown]
* SSLv3, TLS handshake, Finished (20):
} [data not shown]
* SSLv3, TLS change cipher, Client hello (1):
{ [data not shown]
* SSLv3, TLS handshake, Finished (20):
{ [data not shown]
* SSL connection using ECDHE-RSA-AES128-GCM-SHA256
* Server certificate:
* 	 subject: CN=*.geo.admin.ch
* 	 start date: 2017-02-09 00:00:00 GMT
* 	 expire date: 2018-03-09 12:00:00 GMT
* 	 subjectAltName: map.geo.admin.ch matched
* 	 issuer: C=US; O=Amazon; OU=Server CA 1B; CN=Amazon
* 	 SSL certificate verify ok.
> GET /master/688362f/1704261351/1704261351/img/marker.png HTTP/1.1
> User-Agent: curl/7.35.0
> Host: map.geo.admin.ch
> Accept: */*
> 
< HTTP/1.1 200 OK
< Content-Type: image/png
< Content-Length: 808
< Connection: keep-alive
< Date: Fri, 05 May 2017 08:27:38 GMT
< Last-Modified: Mon, 01 May 2017 06:59:03 GMT
< ETag: "4726d3d21bd8711c62b18164d48813eb"
< Cache-Control: max-age=31536000, public
< Accept-Ranges: bytes
* Server AmazonS3 is not blacklisted
< Server: AmazonS3
< Age: 7
< X-Cache: Hit from cloudfront
< Via: 1.1 d8be805548e2ddcdc76c59a729c3cad5.cloudfront.net (CloudFront)
< X-Amz-Cf-Id: _-B2sPlCWBwqnABtGFyJJcbpLb02Llj9lxXoBPNwsvUlrUx_cMjMDA==
< 
{ [data not shown]
100   808  100   808    0     0   9183      0 --:--:-- --:--:-- --:--:--  9287
* Connection #0 to host map.geo.admin.ch left intact

**Comment by danduk82** [comment] 2017-05-05 08:34
mmh, interesting, 
Is the print written in java 6?

If yes the handshake is not working...  We use SNI support on cloudfront, as non-SNI client support is 600$ / month ...

**Comment by gjn** [comment] 2017-05-05 09:01
ref: https://github.com/geoadmin/mf-geoadmin3/issues/3794

Might be SNI related. Seems to be fixed in later versions of the client. We use 3.1, fixed in 4.3. [1]

@procrastinatio The working cloudfront distribution is where? Didn't find it in aws-admin account.

[1] https://issues.apache.org/jira/browse/HTTPCLIENT-1119

**Comment by procrastinatio** [comment] 2017-05-05 10:14
From my understanding, each certificat individually are perfect. CloudFront is also no issue. I just test the faulty code in a simple example, compiled with Java 7, the marker.png (or any image) are downloaded without any trouble in all configuration. No Java issue for me

The problem, is that the print server tries so reuse/cache connection to external images, like markers in vector layer, but also the qrcodeimage, etc.. and under **some** circonstances (to be further investigated), our certificates mix or the order in which the resources are downloaded makes the handshake to fail. I need to test further, but the crux is the qrcodeurl. In most case, if you use http (or the technical address) instead of https for that service, it's fine; if you use api3 after map, it chocks.

This prints OK (only CF icons)
https://s.geo.admin.ch/730362deab

This won't (mix api3 and map)
https://s.geo.admin.ch/730363d1b6

And the same in mf-geoadmin3 fails to load map.geo.admin.ch image!
https://s.geo.admin.ch/730366ad98

And using the technical url is fine:
https://s.geo.admin.ch/730367bbc6

@gjn The CF is in the 2568************* account. I don't have access to the _aws_admin_ console

**Comment by gjn** [comment] 2017-05-05 10:39
Thanks for the clarificatin issue.

Java7 supports SNI, that's why it seems to work. But not sure if we use java7 or java6 for our print.

From what I see, the first example only uses api3 markers - so i'm not surprised that it works.

I have a front-end PR ready soon with a temporary fix. Not sure more investigation is needed.

**Comment by procrastinatio** [comment] 2017-05-05 12:06
We have Java 7. The problem is the mix of api3 and map3, not the certificat or CF _per se_. If for qrcodeurl we use http, the technical url or another domain, we have no issue with the marker.

**Comment by gjn** [comment] 2017-05-05 12:11
So it's a mix of multiple ssl certificates for *.geo.admin.ch domains?

[btw: java and ssl certificates - didn't we have this already?]

**Comment by gjn** [comment] 2017-05-05 12:19
Hmm. very strange.

For map.geo.admin.ch, we have wildcard ssl cert, from amazon: *.geo.admin.ch
![image](https://cloud.githubusercontent.com/assets/2572317/25745131/bd4fd664-319d-11e7-8952-a3b5ff5d7e3b.png)

For api3.geo.admin.ch, we have ssl cert from startcom: wmts.geo.admin.ch
![image](https://cloud.githubusercontent.com/assets/2572317/25745116/a592cc98-319d-11e7-8960-e5e1dc0d1f2a.png)

Maybe installing the amazon wildcard certificate for the api3 domain might fix the problem. @danduk82 @procrastinatio ?

Edit: not startcom for api3, but amazon wildcard certificate for api3 domain.
Edit2: might not be possible as *.geo.admin.ch cert might not support domains like www.map.geo.admin.ch, which the startcom cert does support.

**Comment by hpchrist** [comment] 2017-05-05 15:45
I propose to switch api and api3.geo.admin.ch to the AmazonCert. This would require a DNS switch. Do you agree to plan this for next week?

**Comment by procrastinatio** [comment] 2017-05-05 15:54
Good for me. api.geo.admin.ch is the legacy one, we could use it for testing purpose.

**Comment by gjn** [comment] 2017-05-05 15:58
DNS switch to different ELB (which one)?

Alternatively, could we not replace StartCom Cert with AmazonCert on the existing ELB? Or does the StartCom Cert offer something the AmazonCert would not provide? (not sure about sub.sub.sub.geo.admin.ch domains).

**Comment by hpchrist** [comment] 2017-05-06 20:43
We have an ELB with a Amazon Cert installed instead of the StartCom.

Why not upgrade the StartCom with an AWS cert on the current ELB: damned, I really would like to do it, but there is this MGDI Kadas Stuff that didn't give me the green light yet to do it (they use the WMTS).

Best regards,

Hanspeter

**Comment by procrastinatio** [comment] 2017-05-08 13:24
I have done extensive tests with the following resources:

'https://www.procrastinatio.org/assets/lib/leaflet/images/marker.png' 
'https://map.geo.admin.ch/master/688362f/1704261351/1704261351/img/marker.png' 
'https://dfa30utos8zzp.cloudfront.net/1455526563/img/marker.png' 
'https://mf-geoadmin3.prod.bgdi.ch/master/688362f/1704261351/1704261351/img/marker.png' 
'https://wmts108.geo.admin.ch' 
'https://wmts.geo.admin.ch' 
'https://www.procrastinatio.org/tmp/qrcode.png' 
'https://api3.geo.admin.ch/qrcodegenerator?url=https%3A%2F%2Fmap.geo.admin.ch%2F%3Flang%3Dfr%26topic%3Dech%26bgLayer%3Dch.swisstopo.pixelkarte-farbe%26layers_opacity%3D0.75%26X%3D127456.30%26Y%3D501379.81%26zoom%3D6'

Some observations


* Using the minimal code to download taken from the print server (https://github.com/mapfish/mapfish-print/blob/2.1.x/src/main/java/org/mapfish/print/PDFUtils.java#L210), all resources above may be dowloaded fine with  [apache_download-all-1.0.jar](https://github.com/procrastinatio/mapfish-print-examples/blob/master/bin/apache_download-all-1.0.jar?raw=true). No issue whatsoever. So CF alone or SSL alone are not issue.
* The print server is unable to get any resources behing our CF (wmts100 or map), the resource being alone or with some other resources.
* Apparently, when a resource is not cached, the PDF is OK (timeout after 60s), but missing the marker, otherwise the PDF also broken (impossible to open)
* Marker behind another CF ('dfa30utos8zzp') are just printed fine. So, some CF works.
* Tested with both the standalone print server (locally) or the tomcat version (remote). Same results.
* The only difference between Java7 and Java8 is the version of TLS: TLSv1 vs TLSv12. But both version fail.


More https://github.com/procrastinatio/mapfish-print-examples

**Comment by hpchrist** [comment] 2017-05-08 13:52
Hi 

I have asked the BIT to change the api.geo.admin.ch CNAME.

Old: api.geo.admin.ch CNAME vpc-geo-lb-vpcELB-1U8FPPO5SQ8ZV-1277436068.eu-west-1.elb.amazonaws.com (uses StartCom certificate)

New: api.geo.admin.ch CNAME vpc-geo-wildcard-lb-1731708984.eu-west-1.elb.amazonaws.com (uses Amazon Certificate)

This will enable us to test the Amazon Certificate before we switch api3.geo.admin.ch to the ELB with the Amazon Certificate.

**Comment by procrastinatio** [comment] 2017-05-08 18:40
@hpchrist Already active!

```
$ nslookup api.geo.admin.ch
Non-authoritative answer:
api.geo.admin.ch        canonical name = vpc-geo-wildcard-lb-1731708984.eu-west-1.elb.amazonaws.com.
Name:   vpc-geo-wildcard-lb-1731708984.eu-west-1.elb.amazonaws.com
Address: 52.209.73.195
Name:   vpc-geo-wildcard-lb-1731708984.eu-west-1.elb.amazonaws.com
Address: 54.76.59.39
```

But somewhere (Varnish), there is still a redirect _api.geo.admin.ch(.*)_  on _api**3**.geo.admin.ch/_

**Comment by hpchrist** [comment] 2017-05-09 05:28
Marc, yes, there is stil a redirect in varnish. Please contact Andrea, he will remove the redirect for testing purposes. Best regards, Hanspeter

**Comment by danduk82** [comment] 2017-05-09 14:11
I have changed the varnish rules, and mf1-prod vhost configuration. Now you should be able to test using https://api.geo.admin.ch.

**Comment by gjn** [comment] 2017-05-11 08:56
See https://jira.swisstopo.ch/browse/BGDIINF_SB-476

As soon as Cloudfront is involved, it seems we have a problem. Even all resources behind CF distribution with exactly the same certificate didn't help.

Interesting would be to know why some CF distributions works (as Marc mentioned in his comment).

**Comment by gjn** [comment] 2017-05-11 09:03
I found out that the differenct between the CF that works and the CF that doesn't work is the http2 support. If http2 is supported by the CF distribution, it doesn't work. If only http1 is enabled, then it works:

Open both in browser and look in network tab
[CF that works, shows http1 protocol](https://dfa30utos8zzp.cloudfront.net/1455526563/img/marker.png)
[CF that doesn't work, shows http2 protocol](https://d2ijhfenrpsxab.cloudfront.net/master/10a257a/1705101128/1705101128/img/marker.png)

According to AWS doc, http2/http1 support should be transparent. But it seems that print can't handle it correctly.

**Comment by danduk82** [comment] 2017-05-12 09:56
If the issue is http2, I would recommend using service-print as proxy for the print POST requests, and put into it the "intelligence" to know with backends to use. Then the print should be a fully backend-only solution, thus using direct connection to S3, mapproxy, and mf1 resources.

**Comment by procrastinatio** [comment] 2017-05-23 09:58
One more case:

https://service-proxy.prod.bgdi.ch/http/www.mapplus.ch/core/symbolsets/mapplus/png/restaurants_mountain.png

**Comment by gjn** [comment] 2017-05-23 10:23
Basically, all resources passing via proxy (as it's CF).

Ouch.

What can we do short term?

**Comment by gjn** [comment] 2017-05-23 11:27
@loicgasser @oterral Can we try the 'unproxify' approach in front-end hack?

**Comment by loicgasser** [comment] 2017-05-23 13:57
Yep done in https://github.com/geoadmin/mf-geoadmin3/pull/3816

**Closed as completed** 2017-07-13 07:01 UTC
